# Generated by Django 5.0.6 on 2024-07-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('profileId', models.AutoField(primary_key=True, serialize=False)),
                ('silhouette', models.CharField(max_length=255)),
                ('video', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('life', models.CharField(max_length=255)),
            ],
        ),
    ]
