# Generated by Django 5.0.6 on 2024-07-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profiles',
            table='Profiles',
        ),
    ]
