# Generated by Django 5.0.6 on 2024-07-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
