# Generated by Django 5.0.6 on 2024-07-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
