# Generated by Django 5.0.6 on 2024-07-10 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('story', '0006_story_text'),
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='shop_user',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='visitor_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'Talk',
            },
        ),
        migrations.DeleteModel(
            name='ShopUser',
        ),
        migrations.DeleteModel(
            name='VisitorUser',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
