# Generated by Django 5.0.6 on 2024-07-03 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greats', '0002_alter_greats_table'),
        ('quiz', '0002_alter_quiz_table'),
        ('users', '0006_alter_users_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('statsId', models.AutoField(primary_key=True, serialize=False)),
                ('puzzleCnt', models.IntegerField()),
                ('correctCnt', models.BigIntegerField()),
                ('great', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greats.greats')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'Statistic',
            },
        ),
    ]
