# Generated by Django 5.0.6 on 2024-07-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('silhouette_url', models.CharField(max_length=255)),
                ('photo_url', models.CharField(max_length=255)),
                ('saying', models.TextField()),
                ('nation', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('access_cnt', models.BigIntegerField()),
                ('video_url', models.CharField(max_length=255)),
                ('gender', models.BooleanField()),
                ('life', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Story',
            },
        ),
    ]
