# Generated by Django 5.0.6 on 2024-07-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_story_field_alter_story_life_alter_story_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='gender',
            field=models.BooleanField(choices=[(1, '남성'), (2, '여성')]),
        ),
    ]
