# Generated by Django 5.0.6 on 2024-07-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_alter_story_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='gender',
            field=models.IntegerField(choices=[(1, '남성'), (2, '여성')]),
        ),
    ]
