# Generated by Django 5.0.6 on 2024-07-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_alter_story_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='gender',
            field=models.BooleanField(choices=[(0, '남성'), (1, '여성')]),
        ),
    ]
