# Generated by Django 5.0.6 on 2024-07-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_story_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='access_cnt',
            field=models.BigIntegerField(default=0),
        ),
    ]
