# Generated by Django 5.0.6 on 2024-07-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_alter_story_access_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='story',
            name='text',
        ),
        migrations.AddField(
            model_name='story',
            name='back_url',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='story',
            name='front_url',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='story',
            name='saying_url',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
