# Generated by Django 5.0.6 on 2024-07-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_remove_story_photo_url_remove_story_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='back_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='front_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='saying_url',
            field=models.CharField(max_length=255),
        ),
    ]
