# Generated by Django 5.0.6 on 2024-07-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_alter_story_back_url_alter_story_front_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='information_url',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
