# Generated by Django 5.0.6 on 2024-07-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_story_information_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='information_url',
            field=models.CharField(default='https://www.youtube.com/', max_length=255),
        ),
    ]
