# Generated by Django 5.0.6 on 2024-07-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_alter_story_information_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='information_url',
            field=models.CharField(max_length=255),
        ),
    ]
