# Generated by Django 5.0.6 on 2024-07-26 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_alter_story_information_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='silhouette_url',
        ),
    ]
