# Generated by Django 5.0.6 on 2024-07-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttstask',
            name='file_path',
            field=models.FileField(upload_to='tts_output/'),
        ),
    ]
