# Generated by Django 5.0.6 on 2024-07-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0002_alter_ttstask_file_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TTSTask',
        ),
    ]
